# 模型参数
input_size: 224
embed_dim: 1024
depth: 24
model: crossmae_vit_large
encoder_num_heads: 16
cross_num_heads: 16
mlp_ratio: 4.0
feature_dim: 3
qkv_bias: true
mask_ratio: 0.0

# 评估参数
weights: "./weights/crossmae_vit_large_bs16.pth" # change to your model path
data_path: "./dataset/train_data_0208/val"
batch_size: 8
num_workers: 4
sample_ratio: 0.01
device: "cuda"
output_dir: "./experiment/crossmae/outputs/exp_mr0.0_bias/eval"