# 模型参数
input_size: 224
embed_dim: 768
depth: 12
encoder_num_heads: 12
cross_num_heads: 12
model: multicrossmae_vit_base
mlp_ratio: 4.0
feature_dim: 3
qkv_bias: true
cross_attention: false

# 评估参数
weights: "./weights/multicrossmae_vit_base_vision+touch_0227.pth"
data_path: "./dataset/train_data_0227/train_data_vision+touch"
batch_size: 32
num_workers: 4
pair_downsample: 0.1
device: "cuda"
output_dir: "./experiment/multicrossmae/outputs/exp_mr0.0_bias_rgb+touch_sameed_0227/eval_sr0.1"
curve_type: gaussian
optimizer_type: mse