# 数据集配置
train_image_dir: "./dataset/train_data_0115/train/images"
train_label_dir: "./dataset/train_data_0115/train/labels"
test_image_dir: "./dataset/train_data_0115/val/images"
test_label_dir: "./dataset/train_data_0115/val/labels"

# 训练参数
batch_size: 32
num_workers: 4
epochs: 100
use_cuda: true
pretrained: false
pair_downsample: 0.1

# 模型参数
feature_dim: 3
layer_width: [256, 64]
embedding_width: [64]
using_embedding: true

# 优化器配置
optimizer: "SGD"
optimizer_params:
  lr: 0.01
  momentum: 0.95
  weight_decay: 0.0001

# 数据增强参数
aug_scale: [0.8, 1.0]
aug_flip_prob: 0.5
aug_brightness: 0.2
aug_contrast: 0.2
aug_saturation: 0.2

# 路径配置
checkpoint_dir: "./experiment/checkpoints"
log_dir: "./experiment/logs"

# 设备配置
gpu_id: 0