# 数据集配置
data_path: ./dataset/visionnet_train_0411/vision_touch_mo
# 训练参数
batch_size: 48
epochs: 100     # epochs 增大只会使训练时间变长，不会提高模型性能
input_size: 224 
num_workers: 4
use_fix_template: true

# 模型参数  
model: localmae_vit_base
embed_dim: 768
depth: 12
encoder_num_heads: 12
cross_num_heads: 12 # 头数变大，模型参数变多，训练时间变长，但模型性能基本不变
mlp_ratio: 4
mask_ratio: 0.0 # 在下游任务时，默认不使用mask
feature_dim: 3
qkv_bias: true # 带bias会些许提高模型性能
cross_attention: false
add_noise: false
lambda_start: 0.0
lambda_end: 0.0
lambda_warmup_epochs: 50
sigma: [0.6, 0.3]
method: touch_mask
touch_img_template_path: gel_image_template.png # 需要修改
high_res_size: 560
intensity_scaling: [0.0, 0.6, 0.8, 1.0]
edge_enhancement: 1.5
illumination_alignment: False
beta: 10.0 # 10是最好的
gamma: 1.0
use_chamfer_dist: True
backward_pointcloud_loss: True
use_value_as_weights: True
chamfer_dist_type: 'L2'
# train_noise_ratio: 0.001 # 训练时的噪声比例
# train_noise_level: 0.3 # 训练时的噪声强度
# # 训练时的噪声比例
# val_noise_ratio: 1.0 # 验证时的噪声比例
# val_noise_level: 0.3 # 验证时的噪声强度

# noise_ratio: 0.3
# noise_level: 0.5


# 优化器参数
weight_decay: 0.05
lr: null
blr": 0.001 # 优化器的学习率,学习率太大会收敛变慢，学习率小收敛快_dark，但容易陷入局部最优，减小学习率可以提高模型最终性能
min_lr: 0   # 当回归头层数变少时，学习率变小并没有让模型具有更好的逼近能力
warmup_epochs: 5 # warmup没有太明显的影响，设置1范围为5-10%的范围即可


# 数据增强参数
pair_downsample: 1

# 路径配置
output_dir: "./experiment/new0425/outputs/local_bs48_0411_b100g10_pd_mo_night"
log_dir: "./experiment/new0425/logs/local_bs48_0411_b100g10_pd_mo_night"
mae_pretrained: "./weights/mae_vit_base_vision_1200e_0411_norm.pth"