# 模型参数
model: multicrossmae_vit_base
input_size: 224
embed_dim: 768
depth: 12
encoder_num_heads: 12
cross_num_heads: 12
mlp_ratio: 4.0
feature_dim: 3
qkv_bias: true
cross_attention: false

mask_ratio: 0.0
cross_attention: false
noise_level: 0.0

# 评估参数
weights: "./weights/multicrossmae_vit_base_vision_touch_0227.pth"
data_path: "./dataset/train_data_0227/train_data_vision+touch/"
batch_size: 32
num_workers: 4
pair_downsample: 0.1
device: "cuda"
output_dir: "./experiment/multicrossmae/eval/exp_base_mr0.0_bias_rgb+touch_ba48_0227/eval_sr0.1_new_noise0.0"
curve_type: gaussian
optimizer_type: mse
